# -*- coding: utf-8 -*-
"""CSE422 Lab Project on 'Mental Health on Tech Workplace'

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N9DNNaOTMXd04HpMj3uuirZQX2X-P8yB

# **Start**
"""

import pandas as pd
import numpy as np
import math

import seaborn as sns
import matplotlib.pyplot as plt
import textwrap

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree

from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score, precision_score, f1_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

#from sklearn.feature_extraction.text import CountVectorizer
#from imblearn.over_sampling import RandomOverSample

import warnings
warnings.filterwarnings('ignore')

file_link = "https://drive.google.com/file/d/1wuudhHCfSVTMKMqm8hgri8f98q0q0nEl/view?usp=sharing"
id = file_link.split("/")[-2]
#print(id)
new_link = f'https://drive.google.com/uc?id={id}'
sv = pd.read_csv(new_link)

#sv.head()

"""# **Preprocessing**"""

sv.shape

#sv.head(5)

sv.columns

columns_to_drop = [
    'index',
    'Is your primary role within your company related to techIT',
    'If yes, what conditions have you been diagnosed with',
    'If maybe, what conditions do you believe you have',
    'What is your age',
    "What country do you live in",
    'What US state or territory do you live in',
    "What country do you work in",
    'What US state or territory do you work in',
    'Question',
    'Response']

sv.drop(columns=columns_to_drop, inplace=True)

sv.shape

sv.isnull().sum()

duplicates = sv.duplicated()
sv_cleaned = sv.drop_duplicates()

sv = sv_cleaned
sv.shape

columns_to_encode = ['If so, what conditions were you diagnosed with']

unique_conditions = set()

def extract_conditions(conditions):
    if pd.notna(conditions):
        unique_conditions.update(conditions.split('|'))

for column in columns_to_encode:
    sv[column].apply(extract_conditions)

unique_conditions_list = sorted(unique_conditions)
num_unique_conditions = len(unique_conditions_list)

for condition in unique_conditions_list:
    sv[condition] = sv[columns_to_encode].apply(lambda row: 'Yes' if any(condition in str(item) for item in row) else pd.NA, axis=1)

sv.drop(columns=columns_to_encode, inplace=True)

sv.shape

columns_to_drop = ["PDD-NOS",
                   "ADD (w/o Hyperactivity)",
                   "Asperger Syndrome",
                   "Aspergers",
                   "Attention Deficit Disorder",
                   "Autism (Asperger's)",
                   'Autism - while not a "mental illness", still greatly affects how I handle anxiety',
                   "Autism Spectrum Disorder",
                   "Burn out",
                   "Gender Dysphoria",
                   "Suicidal Ideation",
                   "attention deficit disorder (but not the hyperactive version)",
                   "autism spectrum disorder",
                   "posttraumatic stress disourder",
                   "Gender Identity Disorder",
                   "Intimate Disorder",
                   "PDD-NOS (see above)",
                   "Schizotypal Personality Disorder",
                   "Seasonal Affective Disorder",
                  """MCD (when it was diagnosed, the ultra-mega "disorder" ADHD didn't exist yet)""",
                   "Autism",
                   "Psychotic Disorder (Schizophrenia, Schizoaffective, etc)",
                   "Dissociative Disorder"
                   ]
sv.drop(columns=columns_to_drop, inplace=True)

sv.shape

columns_to_encode = ['Which of the following best describes your work position']

unique_conditions2 = set()

def extract_conditions(conditions):
    if pd.notna(conditions):
        unique_conditions2.update(conditions.split('|'))

for column in columns_to_encode:
    sv[column].apply(extract_conditions)

unique_conditions2_list = sorted(unique_conditions2)
num_unique_conditions2 = len(unique_conditions2_list)

for condition in unique_conditions2_list:
    sv[condition] = sv[columns_to_encode].apply(lambda row: 'Yes' if any(condition in str(item) for item in row) else pd.NA, axis=1)

sv.drop(columns=columns_to_encode, inplace=True)

sv.shape

#sv.isnull().sum()

sv_sub = sv[sv['Question Group'].notnull()]
sv = sv_sub

sv.shape

#sv.info()

sv.drop(columns="ResponseID", inplace=True)

duplicates = sv.duplicated()
sv_cleaned = sv.drop_duplicates()

sv = sv_cleaned
sv.shape

#sv.isnull().sum()

#sv.info()

"""# **Visualisation**"""

positions = ['Back-end Developer',
             'Designer',
             'Dev Evangelist/Advocate',
             'DevOps/SysAdmin',
             'Executive Leadership',
             'Front-end Developer',
             'HR',
             'One-person shop',
             'Other',
             'Sales',
             'Supervisor/Team Lead',
             'Support']

conditions = [
    'Addictive Disorder',
    'Anxiety Disorder (Generalized, Social, Phobia, etc)',
    'Attention Deficit Hyperactivity Disorder',
    'Depression',
    'Eating Disorder (Anorexia, Bulimia, etc)',
    'Mood Disorder (Depression, Bipolar Disorder, etc)',
    'Obsessive-Compulsive Disorder',
    'Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
    'Post-traumatic Stress Disorder',
    'Stress Response Syndromes',
    'Substance Use Disorder']

melted_sv = sv.melt(id_vars=['Have you been diagnosed with a mental health condition by a medical professional'],
                    value_vars = positions,
                    var_name = 'Work Position',
                    value_name = 'Holds Position')

melted_sv = melted_sv[melted_sv['Holds Position'] == 'Yes']

plt.figure(figsize=(14, 6))
ax = sns.countplot(data=melted_sv, x='Work Position', hue='Have you been diagnosed with a mental health condition by a medical professional', palette = 'pastel')

plt.title('Diagnosis of Mental Health Conditions for different Work Positions')
plt.xlabel('Work Position')
plt.ylabel('Frequency')
plt.xticks(rotation=0)
plt.grid(True, linestyle='--', linewidth=0.5, axis='y')

handles, labels = ax.get_legend_handles_labels()
labels = ['Yes' if label == 'True' else 'No' for label in labels]
ax.legend(handles, labels, title='Diagnosed', loc='upper right')

ax.set_xticklabels([textwrap.fill(label.get_text(), 10) for label in ax.get_xticklabels()])

plt.tight_layout()
plt.show()

plt.figure(figsize=(14,6))

ax = sns.countplot(data=sv, x='Question Group', hue='Have you been diagnosed with a mental health condition by a medical professional', palette = 'Set3')

plt.title('Diagnosis of Mental Health Conditions for different Question Group')
plt.xlabel('Question Group')
plt.ylabel('Frequency')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

handles, labels = ax.get_legend_handles_labels()
labels = ['Yes' if label == 'True' else 'No' for label in labels]
ax.legend(handles, labels, title='Diagnosed', loc='upper right')

ax.set_xticklabels([textwrap.fill(label.get_text(), 25) for label in ax.get_xticklabels()], rotation=0)

plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))

ax = sns.countplot(data=sv, x='Question about speaking openly about mental health vs physical health', hue='Have you been diagnosed with a mental health condition by a medical professional', palette='Pastel1')

plt.title('Speaking openly about mental health vs physical health in workplace')
plt.xlabel('Speak openly about mental health vs physical health')
plt.ylabel('Frequency')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

handles, labels = ax.get_legend_handles_labels()
labels = ['Yes' if label == 'True' else 'No' for label in labels]
ax.legend(handles, labels, title='Diagnosed', loc='upper right')

ax.set_xticklabels([textwrap.fill(label.get_text(), 10) for label in ax.get_xticklabels()], rotation=0)

plt.tight_layout()
plt.show()

questions = [
    'Do you have a family history of mental illness',
    'Have you had a mental health disorder in the past',
    'Do you currently have a mental health disorder',
    'Have you ever sought treatment for a mental health issue from a mental health professional']

melted_sv = sv.melt(id_vars=questions, value_vars=conditions, var_name='Condition', value_name='Diagnosed')
melted_sv = melted_sv[melted_sv['Diagnosed'] == 'Yes']

pivot_sv = pd.crosstab(index=melted_sv['Condition'], columns=melted_sv['Do you have a family history of mental illness'])

pivot_sv.plot(kind='barh', stacked=True, figsize=(10, 4), colormap='Accent')
plt.title('Family History of Mental Illness of the Diagnosed')
plt.ylabel('Mental Health Condition')
plt.xlabel('Frequency')
plt.legend(title='Family History of Mental Illness')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='x')
plt.show()

pivot_sv = pd.crosstab(index=melted_sv['Condition'],columns=melted_sv['Have you had a mental health disorder in the past'])

pivot_sv.plot(kind='barh', stacked=True, figsize=(10, 4), colormap='Accent')
plt.title('Past Mental Health Disorder of the Diagnosed')
plt.ylabel('Mental Health Condition')
plt.xlabel('Frequency')
plt.legend(title='Past Mental Health Disorder')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='x')
plt.show()

pivot_sv = pd.crosstab(index=melted_sv['Condition'],columns=melted_sv['Do you currently have a mental health disorder'])

pivot_sv.plot(kind='barh', stacked=True, figsize=(10, 4), colormap='Accent')
plt.title('Current Mental Health Disorder of the Diagnosed')
plt.ylabel('Mental Health Condition')
plt.xlabel('Frequency')
plt.legend(title='Current Mental Health Disorder')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='x')
plt.show()

pivot_sv = pd.crosstab(index=melted_sv['Condition'],columns=melted_sv['Have you ever sought treatment for a mental health issue from a mental health professional'])

pivot_sv.plot(kind='barh', stacked=True, figsize=(10, 4), colormap='Accent')
plt.title('Treatment taken for Mental Health Issue by the Diagnosed')
plt.ylabel('Mental Health Condition')
plt.xlabel('Frequency')
plt.legend(title='Sought Treatment')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='x')
plt.show()

columns_to_drop = ['Question Group',
                   'Question about speaking openly about mental health vs physical health',
                   'Back-end Developer',
                   'Designer',
                   'Dev Evangelist/Advocate',
                   'DevOps/SysAdmin',
                   'Executive Leadership',
                   'Front-end Developer',
                   'HR',
                   'One-person shop',
                   'Other',
                   'Sales',
                   'Supervisor/Team Lead',
                   'Support'
                   ]

sv.drop(columns=columns_to_drop, inplace=True)

"""# **Encoding**"""

#sv.info()

sv["How many employees does your company or organization have"].unique()

mapping = {None: 0, '1-5': 1,'6-25': 2,'26-100': 3,'100-500': 4,'500-1000': 5,'More than 1000': 6}
sv['How many employees does your company or organization have'] = sv['How many employees does your company or organization have'].replace(mapping)

sv["Is your employer primarily a tech companyorganization"].unique()

sv['Is your employer primarily a tech companyorganization'].fillna('Unknown', inplace=True)

mapping ={False:0, 'Unknown':1, True:2}
sv['Is your employer primarily a tech companyorganization'] = sv['Is your employer primarily a tech companyorganization'].replace(mapping)

sv["Do you have a family history of mental illness"].unique()

sv['Do you have a family history of mental illness'] = sv["Do you have a family history of mental illness"].map({'No':0, "I don't know":1, 'Yes':2})

sv["Have you had a mental health disorder in the past"].unique()

sv['Have you had a mental health disorder in the past'] =sv["Have you had a mental health disorder in the past"].map({'No':0,'Maybe':1,'Yes':2})

sv["Do you currently have a mental health disorder"].unique()

sv['Do you currently have a mental health disorder'] =sv["Do you currently have a mental health disorder"].map({'No':0, 'Maybe':1, 'Yes':2})

sv.columns = sv.columns.str.strip()
sv['What is your gender'].unique()

sv['What is your gender'] =sv['What is your gender'].map({'Male':0, 'Female':1, 'Trans/Other':2})

sv["Age Group"].unique()

sv['Age Group'] = sv['Age Group'].map({'Under 20':0,'20-25':1, "26-30":1,"31-35":2,"36-40":2,"41-45":3,"46-50":3, '51-55':4,'56-60':4,'61-65':4,'Over 65':5 })

sv["Do you work remotely"].unique()

sv['Do you work remotely'] = sv["Do you work remotely"].map({'Never':0, 'Sometimes':1, 'Always':2})

sv["Addictive Disorder"].unique()

sv['Addictive Disorder'] = sv['Addictive Disorder'].map({'Yes': 1, pd.NA: 0})

sv["Anxiety Disorder (Generalized, Social, Phobia, etc)"].unique()

sv["Anxiety Disorder (Generalized, Social, Phobia, etc)"] = sv["Anxiety Disorder (Generalized, Social, Phobia, etc)"].map({'Yes': 1, pd.NA: 0})

sv["Attention Deficit Hyperactivity Disorder"].unique()

sv["Attention Deficit Hyperactivity Disorder"] = sv["Attention Deficit Hyperactivity Disorder"].map({'Yes': 1, pd.NA: 0})

sv["Depression"].unique()

sv["Depression"] = sv["Depression"].map({'Yes': 1, pd.NA: 0})

sv["Eating Disorder (Anorexia, Bulimia, etc)"].unique()

sv["Eating Disorder (Anorexia, Bulimia, etc)"] = sv["Eating Disorder (Anorexia, Bulimia, etc)"].map({'Yes': 1, pd.NA: 0})

sv["Mood Disorder (Depression, Bipolar Disorder, etc)"].unique()

sv["Mood Disorder (Depression, Bipolar Disorder, etc)"] = sv["Mood Disorder (Depression, Bipolar Disorder, etc)"].map({'Yes': 1, pd.NA: 0})

sv["Obsessive-Compulsive Disorder"].unique()

sv["Obsessive-Compulsive Disorder"] = sv["Obsessive-Compulsive Disorder"].map({'Yes': 1, pd.NA: 0})

sv["Personality Disorder (Borderline, Antisocial, Paranoid, etc)"].unique()

sv["Personality Disorder (Borderline, Antisocial, Paranoid, etc)"] = sv["Personality Disorder (Borderline, Antisocial, Paranoid, etc)"].map({'Yes': 1, pd.NA: 0})

sv["Post-traumatic Stress Disorder"].unique()

sv["Post-traumatic Stress Disorder"] = sv["Post-traumatic Stress Disorder"].map({'Yes': 1, pd.NA: 0})

sv["Stress Response Syndromes"].unique()

sv["Stress Response Syndromes"] = sv["Stress Response Syndromes"].map({'Yes': 1, pd.NA: 0})

sv["Substance Use Disorder"].unique()

sv["Substance Use Disorder"] = sv["Substance Use Disorder"].map({'Yes': 1, pd.NA: 0})

#sv.info()

#sv.head(20)

"""# **More Visualisation**"""

age_group_conditions = pd.DataFrame()

for condition in conditions:
    if condition in sv.columns:
        summed_data = sv.groupby('Age Group')[condition].sum()
        age_group_conditions[condition] = summed_data

fig, ax = plt.subplots(figsize=(10, 10))
age_group_conditions.plot(kind='bar', ax=ax, colormap='viridis')

plt.title('Mental Health Conditions Across Age Groups')
plt.xlabel('Age Group')
plt.ylabel('Number of Cases')
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

ax.set_xticklabels(['Under 20', '20-30', '31-40', '44-50', '51-65', 'Over 65'], rotation=0)
ax.legend(title='Conditions', bbox_to_anchor=(0.5, -0.1), loc='upper center', ncol=2)

plt.tight_layout()
plt.show()

gender_conditions = pd.DataFrame()

for condition in conditions:
    if condition in sv.columns:
        summed_data = sv.groupby('What is your gender')[condition].sum()
        gender_conditions[condition] = summed_data

fig, ax = plt.subplots(figsize=(10, 10))
gender_conditions.plot(kind='bar', ax=ax, colormap='viridis')

plt.title('Mental Health Conditions Across different Gender')
plt.xlabel('Gender')
plt.ylabel('Number of Cases')
plt.xticks(rotation=45)
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

ax.set_xticklabels(['Male', 'Female', 'Trans/Other'], rotation=0)
ax.legend(title='Conditions', bbox_to_anchor=(0.5, -0.1), loc='upper center', ncol=2)

plt.tight_layout()
plt.show()

ctab = pd.crosstab(sv['Are you selfemployed'], sv['Have you been diagnosed with a mental health condition by a medical professional'])

colors = sns.color_palette('Paired', n_colors=2)

ctab.plot(kind='bar',  color=colors)
plt.title('Diagnosis of Mental Health Conditions across employment type')
plt.xlabel('Are you self employed')
plt.ylabel('Frequency')
plt.legend(title='Diagnosed')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

labels = ['No', 'Yes']
plt.xticks(ticks=[0, 1], labels=labels, rotation=0)

plt.show()

ctab = pd.crosstab(sv['Are you selfemployed'], sv['Have you been diagnosed with a mental health condition by a medical professional'])

colors = sns.color_palette('Accent', n_colors=2)

ctab.plot(kind='bar', color = colors)
plt.title('Diagnosis of Mental Health Conditions across employment type')
plt.xlabel('Are you self employed')
plt.ylabel('Frequency')
plt.legend(title='Diagnosed')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

labels = ['No', 'Yes']
plt.xticks(ticks=[0, 1], labels=labels, rotation=0)
plt.show()

ctab = pd.crosstab(sv['How many employees does your company or organization have'], sv['Have you been diagnosed with a mental health condition by a medical professional'])

colors = sns.color_palette('Pastel1', n_colors=2)

ctab.plot(kind='bar', figsize = (10,4),color=colors)
plt.title('Diagnosis of Mental Health Conditions for different Company Size')
plt.xlabel('Number of employees in the company/organization')
plt.ylabel('Frequency')
plt.legend(title='Diagnosed', bbox_to_anchor=(0.25, 1))
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

labels = ['None','1-5', '6-25', '26-100', '100-500', '500-1000',  'More than 1000']
plt.xticks(ticks=[0, 1, 2, 3, 4, 5, 6], labels=labels, rotation=0)
plt.show()

ctab = pd.crosstab(sv['Is your employer primarily a tech companyorganization'], sv['Have you been diagnosed with a mental health condition by a medical professional'])

colors = sns.color_palette('Set3', n_colors=2)

ctab.plot(kind='bar', color=colors)
plt.title('Diagnosis of Mental Health Conditions across Company type')
plt.xlabel('Is is a Tech Company')
plt.ylabel('Frequency')
plt.legend(title='Diagnosed')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

labels = ['No', 'Not Sure', 'Yes']
plt.xticks(ticks=[0, 1, 2], labels=labels, rotation=0)
plt.show()

ctab = pd.crosstab(sv['Do you have previous employers'], sv['Have you been diagnosed with a mental health condition by a medical professional'])

colors = sns.color_palette('PiYG', n_colors=4)

ctab.plot(kind='bar', color=colors)
plt.title('Diagnosis of Mental Health Conditions for varying Experience')
plt.xlabel('First job')
plt.ylabel('Frequency')
plt.legend(title='Diagnosed')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

labels = ['Yes', 'No']
plt.xticks(ticks=[0, 1], labels=labels, rotation=0)
plt.show()

ctab = pd.crosstab(sv['Do you work remotely'], sv['Have you been diagnosed with a mental health condition by a medical professional'])

colors = sns.color_palette('PiYG', n_colors=2)

ctab.plot(kind='bar', color=colors)
plt.title('Diagnosis of Mental Health Conditions across work type')
plt.xlabel('Remote Work')
plt.ylabel('Frequency')
plt.legend(title='Diagnosed')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')

labels = ['Never', 'Sometimes', 'Always']
plt.xticks(ticks=[0, 1, 2], labels=labels, rotation=0)

plt.show()

"""# **Feature Selection**"""

#sv.columns

import seaborn as sns
co = sv.corr()
sns.heatmap(co)

correlation_matrix = sv.corr()
target_correlation = correlation_matrix['Have you been diagnosed with a mental health condition by a medical professional']
print(target_correlation)

to_drop = ['Do you have previous employers',
           'Are you selfemployed',
           'How many employees does your company or organization have',
           'Is your employer primarily a tech companyorganization',
           'Age Group',
           'Do you work remotely',
       ]
selected_features = sv.drop(to_drop, axis=1)

sv = selected_features

import seaborn as sns
co = sv.corr()
sns.heatmap(co, cmap = "BuPu")

#sv.columns

"""# **Test-Train Split**"""

feature_cols = ['Do you have a family history of mental illness',
                'Have you had a mental health disorder in the past',
                'Do you currently have a mental health disorder',
                'Have you ever sought treatment for a mental health issue from a mental health professional',
                'What is your gender',
                'Addictive Disorder',
                'Anxiety Disorder (Generalized, Social, Phobia, etc)',
                'Attention Deficit Hyperactivity Disorder', 'Depression',
                'Eating Disorder (Anorexia, Bulimia, etc)',
                'Mood Disorder (Depression, Bipolar Disorder, etc)',
                'Obsessive-Compulsive Disorder',
                'Personality Disorder (Borderline, Antisocial, Paranoid, etc)',
                'Post-traumatic Stress Disorder',
                'Stress Response Syndromes',
                'Substance Use Disorder']

y = pd.DataFrame(sv['Have you been diagnosed with a mental health condition by a medical professional'])
X_train, X_test, y_train, y_test = train_test_split(sv[feature_cols], sv['Have you been diagnosed with a mental health condition by a medical professional'], test_size = 0.2, random_state=0, stratify = y)

print(X_train.shape)
print(X_test.shape)

co = sv.corr()
sns.heatmap(co,cmap = 'YlGnBu')

X_test.head(5)

X_features = sv.drop('Have you been diagnosed with a mental health condition by a medical professional', axis=1)

"""# **Models**"""

# Logistic Regression

lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

lr_train_score =  lr.score(X_train, y_train)
lr_test_score = lr.score(X_test, y_test)

print("Logistic Regression\n")
print(f"Training accuracy: {lr_train_score}")
print(f"Testing accuracy: {lr_test_score}")

# Random Forest Classifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

rf_train_score = rf.score(X_train, y_train)
rf_test_score = rf.score(X_test, y_test)

print("Random Forest Classifier\n")
print(f"Training accuracy: {rf_train_score}")
print(f"Testing accuracy: {rf_test_score}")

chosen_tree = rf.estimators_[0]

plt.figure(figsize=(20,8))
tree.plot_tree(chosen_tree,
               feature_names=X_train.columns,
               class_names=['Not Diagnosed', 'Diagnosed'],
               filled=True,
               max_depth=4,
               fontsize=10)

plt.title('Visualization of a Single Tree in Random Forest')
plt.show()

# Gradient Boosting Classifier

gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
gb.fit(X_train, y_train)
y_pred_gb = gb.predict(X_test)

gb_train_score = gb.score(X_train, y_train)
gb_test_score = gb.score(X_test, y_test)

print("Gradient Boosting Classifier\n")
print(f"Training accuracy: {gb_train_score}")
print(f"Testing accuracy: {gb_test_score}")

# K-Nearest Neighbors

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

knn_train_score = knn.score(X_train, y_train)
knn_test_score = knn.score(X_test, y_test)

print("K-Nearest Neighbors\n")
print(f"Training accuracy: {knn_train_score}")
print(f"Testing accuracy: {knn_test_score}")

# Accuracy comparing graph

labels = ["Logistic Regression", "Random Forest Classifier", "Gradient Boosting Classifier", "K-Nearest Neighbors"]

train_acc = [lr_train_score*100, rf_train_score*100, gb_train_score*100, knn_train_score*100]
test_acc = [lr_test_score*100, rf_test_score*100, gb_test_score*100, knn_test_score*100]

train_acc = np.array(train_acc, dtype=int)
test_acc = np.array(test_acc, dtype=int)

x = np.arange(len(labels))
width = 0.35

fig, ax = plt.subplots(figsize=(10, 5))
plt.grid(True, linestyle='--', linewidth=0.5, color='gray', axis='y')
rects1 = ax.bar(x - width/2, train_acc, width, label="Training Accuracy", color='skyblue')
rects2 = ax.bar(x + width/2, test_acc, width, label="Testing Accuracy", color='lightgreen')

ax.set_title('Training and Testing Accuracies for different ML Models')
ax.set_ylabel("Accuracy")
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend(loc='upper center', bbox_to_anchor=(0.45, -0.1), fancybox=True, shadow=True, ncol=2)



def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate('{}'.format(round(height, 2)),
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom')

autolabel(rects1)
autolabel(rects2)

fig.tight_layout()
plt.show()

def display_confusion_matrix(cf_matrix, model_name, color_map='Blues'):
    dataframe_cfm = pd.DataFrame(cf_matrix, index=[0, 1], columns=[0, 1])
    plt.figure(figsize=(7, 5))
    ax = sns.heatmap(dataframe_cfm, annot=True, fmt='d', cmap=color_map)
    ax.set_title(f'Confusion Matrix for {model_name}\n')
    ax.set_xlabel('\nPredicted Label')
    ax.set_ylabel('Actual Label')
    ax.xaxis.set_ticklabels(['Not Diagnosed', 'Diagnosed'])
    ax.yaxis.set_ticklabels(['Not Diagnosed', 'Diagnosed'])
    plt.show()

# Logistic Regression

precision_scores = precision_score(y_test, lr.predict(X_test), average='binary')
recall_scores  = recall_score(y_test, lr.predict(X_test), average='binary')
f1_scores = f1_score(y_test, lr.predict(X_test), average='binary')

print("Logistic Regression\n")
print("Precision Score:", precision_scores)
print("Recall Score:", recall_scores)
print("F1 Score:", f1_scores, '\n')

lr_cf_matrix = confusion_matrix(y_test, y_pred_lr)
display_confusion_matrix(lr_cf_matrix, "Logistic Regression","Reds")

# Random Forest Classifier

precision_scores = precision_score(y_test, rf.predict(X_test), average='binary')
recall_scores  = recall_score(y_test, rf.predict(X_test), average='binary')
f1_scores = f1_score(y_test, rf.predict(X_test), average='binary')

print("Random Forest Classifier\n")
print("Precision Score:", precision_scores)
print("Recall Score:", recall_scores)
print("F1 Score:", f1_scores, '\n')

rf_cf_matrix = confusion_matrix(y_test, y_pred_rf)
display_confusion_matrix(rf_cf_matrix, "Random Forest Classifier","Greens")

# Gradient Boosting Classifier

precision_scores = precision_score(y_test, gb.predict(X_test), average='binary')
recall_scores  = recall_score(y_test, gb.predict(X_test), average='binary')
f1_scores = f1_score(y_test, gb.predict(X_test), average='binary')

print("Gradient Boosting Classifier\n")
print("Precision Score:", precision_scores)
print("Recall Score:", recall_scores)
print("F1 Score:", f1_scores, '\n')

gb_cf_matrix = confusion_matrix(y_test, y_pred_gb)
display_confusion_matrix(gb_cf_matrix, "Gradient Boosting Classifier","Blues")

# K-Nearest Neighbors

precision_scores = precision_score(y_test, knn.predict(X_test), average='binary')
recall_scores  = recall_score(y_test, knn.predict(X_test), average='binary')
f1_scores = f1_score(y_test, knn.predict(X_test), average='binary')

print("K-Nearest Neighbors\n")
print("Precision Score:", precision_scores)
print("Recall Score:", recall_scores)
print("F1 Score:", f1_scores, '\n')

knn_cf_matrix = confusion_matrix(y_test, y_pred_knn)
display_confusion_matrix(knn_cf_matrix, "K-Nearest Neighbors","BuPu")