# -*- coding: utf-8 -*-
"""CSE422 Lab Project Group 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1I7grMcw6CFUdk5ScgzSkDGSmyyeajg
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

from google.colab import drive
drive.mount('/content/gdrive')

survey = pd.read_csv('/content/OSMI_Survey_Data.csv')
survey.head(5)

survey.shape

"""### Preprocessing"""

survey.isnull().sum()

to_drop = ["index", "ResponseID","How many employees does your company or organization have","Is your primary role within your company related to techIT", "What US state or territory do you live in", "What US state or territory do you work in", "Question Group", "Question", "Response"]
survey = survey.drop(to_drop, axis=1)

survey.shape

survey.isnull().sum()

print("Null entries for What is your age:", survey['What is your age'].isnull().sum())
survey_subset = survey[survey['What is your age'].notnull()]
print("Shape after removing null values:", survey_subset.shape)

survey = survey_subset
survey.isnull().sum()

print("Null entries for Is your employer primarily a tech companyorganization:", survey['Is your employer primarily a tech companyorganization'].isnull().sum())
survey_subset = survey[survey['Is your employer primarily a tech companyorganization'].notnull()]
print("Shape after removing null values:", survey_subset.shape)

survey = survey_subset
survey.isnull().sum()

"""### Encoding"""

survey.info()

survey['Is your employer primarily a tech companyorganization'].unique()

from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
survey['Is your employer primarily a tech companyorganization'] = enc.fit_transform(survey['Is your employer primarily a tech companyorganization'])

survey['Do you have a family history of mental illness'].unique()

survey['Do you have a family history of mental illness'] = survey['Do you have a family history of mental illness'].map({'No':0,"I don't know":1,'Yes':2 })

survey['Have you had a mental health disorder in the past'].unique()

survey['Have you had a mental health disorder in the past'] = survey['Have you had a mental health disorder in the past'].map({'No':0,"Maybe":1,'Yes':2 })

survey['Do you currently have a mental health disorder'].unique()

survey['Do you currently have a mental health disorder'] = survey['Do you currently have a mental health disorder'].map({'No':0,"Maybe":1,'Yes':2 })

survey['Age Group'].unique()

survey['Age Group'] = survey['Age Group'].map({'Under 20':0,'20-25':0, "26-30":1,"31-35":1,"36-40":1,"41-45":1,"46-50":1, '51-55':2,'56-60':2,'61-65':2,'Over 65':2 })

survey['Do you work remotely'].unique()

survey['Do you work remotely'] = survey['Do you work remotely'].map({'Never':0,"Sometimes":1,'Always':2 })

survey['Question about speaking openly about mental health vs physical health'].unique()

from sklearn.preprocessing import LabelEncoder

enc = LabelEncoder()
survey['Question about speaking openly about mental health vs physical health'] = enc.fit_transform(survey['Question about speaking openly about mental health vs physical health'])

#survey['If yes, what conditions have you been diagnosed with'].unique()
#survey['If maybe, what conditions do you believe you have'].unique()
#survey['If so, what conditions were you diagnosed with'].unique()
#survey['Which of the following best describes your work position'].unique()

survey.head(5)

survey.info()

"""### Feature Selection"""

import seaborn as sns
co = survey.corr()
sns.heatmap(co,cmap = 'YlGnBu')

survey.columns

to_drop = ['Do you have previous employers', 'If yes, what conditions have you been diagnosed with',
       'If maybe, what conditions do you believe you have','If so, what conditions were you diagnosed with',
       'What is your age','What is your gender ','What country do you live in', 'What country do you work in',
       'Which of the following best describes your work position']
selected_features = survey.drop(to_drop, axis=1)

survey = selected_features

survey.shape

survey.info()

survey.head(5)

"""### Test-Train Split"""

#Stratified data splitting

from sklearn.model_selection import train_test_split

feature_cols = ['Are you selfemployed',
       'Is your employer primarily a tech companyorganization',
       'Do you have a family history of mental illness',
       'Have you had a mental health disorder in the past',
       'Have you been diagnosed with a mental health condition by a medical professional',
       'Have you ever sought treatment for a mental health issue from a mental health professional',
       'Age Group', 'Do you work remotely',
       'Question about speaking openly about mental health vs physical health']

y = pd.DataFrame(survey['Do you currently have a mental health disorder']) # Target variable
X_train, X_test, y_train, y_test = train_test_split(survey[feature_cols], survey['Do you currently have a mental health disorder'], test_size = 0.2, random_state=0, stratify = y)

print(X_train.shape)
print(X_test.shape)

X_test.head(5)

X_features = survey.drop('Do you currently have a mental health disorder', axis=1)
#Y_target = survey['Do you currently have a mental health disorder']

"""### Models"""

#Descision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt = DecisionTreeClassifier(criterion='entropy',random_state=1)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
dt_score = accuracy_score(y_pred_dt,y_test)

print(f"DT Accuracy: {dt_score:.2f}")

from sklearn import tree
import matplotlib.pyplot as plt

fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=750)
tree.plot_tree(dt,
               feature_names = X_features.columns,
               class_names=['0','1','2','3'],
               filled = True);

from sklearn import metrics

confusion_matrix = metrics.confusion_matrix(y_test,y_pred_dt)
cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix)

cm_display.plot()
plt.show()

#KNN

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Create kNN classifier
k = 5  # Number of neighbors
knn_classifier = KNeighborsClassifier(n_neighbors=k)

# Train the classifier
knn_classifier.fit(X_train, y_train)

# Make predictions
y_pred_knn = knn_classifier.predict(X_test)
knn_score = accuracy_score(y_test, y_pred_knn)
print(f"KNN Accuracy: {knn_score:.2f}")

from sklearn import metrics

confusion_matrix = metrics.confusion_matrix(y_test,y_pred_knn)
cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix)

cm_display.plot()
plt.show()

#Logistic Regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)
lr_score = accuracy_score(y_pred_lr,y_test)

print(f"LR Accuracy: {lr_score:.2f}")

from sklearn import metrics

confusion_matrix = metrics.confusion_matrix(y_test,y_pred_lr)
cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = confusion_matrix)

cm_display.plot()
plt.show()

data={'DT':dt_score, 'KNN':knn_score, 'LR':lr_score}

models=list(data.keys())
scores=list(data.values())
fig = plt.figure(figsize = (10, 5))
plt.bar(models,scores, width=0.5)

plt.xlabel("Model name")
plt.ylabel("Accuracy score")
plt.title("Models used and their accuracies")
plt.show()